version: "3.7"

services:	
    
  advert-board-api:
    build:
      dockerfile: src/AdvertBoard/Hosts/AdvertBoard.Api/Dockerfile
    ports:
      - 5000
    environment:
      - ConnectionStrings_PostgresAdvertBoardDb=Host=localhost;Database=AdvertBoard;Username=postgres;Password=2012
    depends_on:
      - postgres


  postgres:
    image: "postgres" # use latest official postgres version
    restart: always
    environment: # configure postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=AdvertBoard
        - POSTGRES_PASSWORD=2012
    ports:
        - "5432:5432"
    volumes: #persist data even if container shuts down
        - postgres_data:/var/lib/postgresql/data/

volumes: #named volumes can be managed easier using docker-compose
  postgres_data:	
